### ISSUE TITLE
To-do list for Week 2

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_group-106_supermarket#26]
The intent is to create a MVP that is standalone and submittable in case we can't figure out the by department functionality for the bar charts. 

**Minimum Viable Product**

- [x] Set up structure of dashboard in .py document including: dropdown for stores, functions to create chart, functionality based on the dropdown (Tuesday night: Reiko will try; Wednesday morning: Monique to take over)
- [x] Set up Heroku: add necessary files and link GitHub repo to deploy dashboard (Monique to do Thurs morning if .py is working)
- [x] Fix formatting, spacing, titles as necessary (currency, scale of customer satisfaction)

**By department functionality**

- [x] Create Altair bar charts on separate Jupyter notebook (by Wednesday 4pm - Clara will try)
- [x] Create (separate?) or add to separate .py file for interactivity of bar charts (Thursday in lab)

**Submission instructions**

- [x] Document the functionality of your Dash app in the README.md file (Monique)
- [x] Reflection:  critique your dashboard and point out what it does well, what its limitations are, and what are good future improvements and additions. In this section, you should also clearly document how you addressed the feedback (GitHub issues) you received from your peers and the TAs (Monique)

**Comment by reikookamoto** [comment]
Also adding this here:
- [ ] PEP-8 docstrings for functions
- [ ] Tool tips: decimal places? Also removed '$' from tool tip in the heat map since that was being used across all the heat maps.
- [ ] Show actual branch names instead of A, B, and C?
- [ ] Set defaults for heatmaps and barplots
- [ ] Choose and stick to single versus double quotations where possible!

**Comment by reikookamoto** [comment]
Hi @moniquewong! Just read over the group reflection and wanted to make a few comments.
- When treating 'by department' as an adjective (e.g. "... compare by department performance", "... repeating the by department visualizations"), I think it's better to put a hyphen between the two words. Alternatively, "department-specific" could be used here.
-  If the word count permits, you could further explain how our dashboard is self-documenting in the section 'is simple to understand.' We could mention that appropriate labels were used for the radio buttons and dropdown menus and descriptive titles were provided for the figures. But maybe not necessary if we're tight on word count.
- Should we say something here about how the 2 x 4 display only works when you're on a computer with a large enough display? The heat maps in the first row wraps around when you have it open on a small screen.
- A few words of how we responded to the GitHub issues from Ellen. Could you maybe include how we divided the work this week? I worked on the basic heat map, you worked on the first set of interactivity (and the reflection!), and @clsu22 worked on the bar plots.

**Comment by moniquewong** [comment]
@reikookamoto Prioritizing adding addressing GitHub issues and fixing "by department" language. We're quite close to the word limit!

**Comment by moniquewong** [comment]
Made changes and created pull request
