### ISSUE TITLE
To-do list for Week 1

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/DSCI_532_group-106_supermarket#6]
- [x] Code of conduct (Reiko)
- [x]  Proposal 1: Motivation and purpose (Monique)
- [x]  Proposal 2: Description of data (Clara)
- [x]  Proposal 3: Resesearch question (Monique)
- [x]  Proposal 3: Usage scenario (Reiko)
- [x]  Sketch (Reiko)
- [x]  Team contract (Clara); **this should be github.ubc.ca**
- Internal deadline: Friday 7 pm 
- Group call on Slack: Saturday noon
